project_id = "wlmvzdhvvbbqidhvrdsh"

[functions.vps-status]
verify_jwt = false

[functions.server-monitor]
verify_jwt = false

[functions.keep-alive]
verify_jwt = false

[functions.container-action]
verify_jwt = false
