name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # التوجه لمسار المشروع في السيرفر
            cd ~/amarvps
            
            # سحب أحدث التعديلات من GitHub
            git pull origin main
            
            # إعادة بناء الحاوية وتشغيلها في الخلفية بدون sudo
            docker compose up -d --build
            
            # تنظيف صور Docker القديمة غير المستخدمة لتوفير المساحة بدون sudo
            docker image prune -f